# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
- staging
- dev

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  projects: '**/**/*.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  isPR: $[eq(variables.Build.Reason, 'PullRequest')]
  isMerge: $[eq(variables.Build.Reason, 'merge')]
  version: $[if(variables.isMerge && eq(variables['system.PullRequest.targetBranch']), variables['alphaVersionEnvVar'], if(variables.isMerge && eq(variables['system.PullRequest.targetBranch']), variables['betaVersionEnvVar'], if (variables.isMerge && eq(variables.system.targetBranch, 'master'),variables['releaseVersionEnvVar'],'')))]

steps:

- task: NuGetToolInstaller@1
  displayName: 'nuget install'
  inputs:
    versionSpec: 
    checkLatest: true

- task: NuGetCommand@2
  displayName: 'nuget restore'
  inputs:
    command: 'restore'
    restoreSolution: '**/**/*.sln'
    feedsToUse: 'select'

- task: MSBuild@1
  displayName: 'build PR using msbuild'
  inputs:
    solution: '**/*.sln'  
    msbuildArchitecture: 'x64'
    platform: 'Any CPU'
    configuration: '$(buildConfiguration)'
  condition: and(succeeded(), eq(variables.isPR, true))

- task: MSBuild@1
  displayName: 'build merge using msbuild'
  inputs:
    solution: '**/*.sln'
    msbuildArguments: '-t:Pack -p:PackageVersion=$(version)'    
    msbuildArchitecture: 'x64'
    platform: 'Any CPU'
    configuration: '$(buildConfiguration)'
  condition: and(succeeded(), eq(variables.isMerge, true))

- task: NuGetCommand@2
  displayName: 'nuget setApiKey'
  inputs:
    command: 'custom'
    arguments: 'setApiKey $(nugetCredential)'
  condition: and(succeeded(), eq(variables.isMerge, true))

- task: NuGetCommand@2
  displayName: 'nuget push'
  inputs:
    command: 'push'
    arguments: '-SkipIfAlreadyPublished -SkipDuplicate'
    feedsToUse: 'config'    
    externalFeedCredentials: '$(externalFeedCredentials)' 
    publishFeedCredentials: '$(publishFeedCredentials)'    
    packagesToPush: '.net/src/DevSkill.SSLCommerz/DevSkill.SSLCommerz.Core/bin/Release/*.nu*;!.net/src/DevSkill.SSLCommerz/DevSkill.SSLCommerz.Core/bin/Release/*.symbols.nu*'
    nuGetFeedType: 'external'
    publishVstsFeed: 'DevSkill.SSLCommerz.Core'
    versioningScheme: 'byEnvVar'
    versionEnvVar: '$(versionEnvVar)'
    allowPackageConflicts: false
  condition: and(succeeded(), eq(variables.isMergeBuildable, true))
