# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
- staging
- dev

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  projects: '**/**/*.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore *.csproj'
  inputs:
    command: 'restore'
    projects: '**/**/*.csproj'
    workingDirectory: '.net/src'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build *.csproj'
  inputs:
    command: 'build'
    projects: '**/**/*.csproj'
    workingDirectory: '.net/src'

- task: NuGetToolInstaller@1
  displayName: 'nuget install'
  inputs:
    versionSpec: 
    checkLatest: true

- task: NuGetCommand@2
  displayName: 'nuget restore'
  inputs:
    command: 'restore'
    restoreSolution: '**/**/*.sln'
    feedsToUse: 'select'

- task: MSBuild@1
  displayName: 'msbuild *.csproj'
  inputs:
    solution: '**/**/*.csproj'
    msbuildArchitecture: 'x64'
    platform: 'Any CPU'
    configuration: 'Debug'
    workingDirectory: '.net/src'

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack DevSkill.SSLCommerz.Core'
  inputs:
    command: 'pack'
    arguments: '--configuration $(buildConfiguration)'
    packagesToPack: '**/DevSkill.SSLCommerz.Core/DevSkill.SSLCommerz.Core.csproj'
    nobuild: true
    versioningScheme: 'off'
    workingDirectory: '.net/src'

- task: NuGetCommand@2
  displayName: 'nuget push'
  inputs:
    command: 'push'
    feedsToUse: 'select'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishVstsFeed: 'DevSkill.SSLCommerz.Core'
    versioningScheme: 'off'
    allowPackageConflicts: true
