# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
- staging
- dev

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  projects: '**/**/*.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore *.csproj'
  inputs:
    command: 'restore'
    arguments: '-c $(buildConfiguration)'
    projects: '**/**/*.csproj'
    workingDirectory: '.net/src'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build *.csproj'
  inputs:
    command: 'build'
    arguments: '-c $(buildConfiguration)'
    projects: '**/**/*.csproj'
    workingDirectory: '.net/src'

- task: NuGetToolInstaller@1
  displayName: 'nuget install'
  inputs:
    versionSpec: 
    checkLatest: true

- task: NuGetCommand@2
  displayName: 'nuget restore'
  inputs:
    command: 'restore'
    restoreSolution: '**/**/*.sln'
    feedsToUse: 'select'

- task: MSBuild@1
  displayName: 'msbuild *.csproj'
  inputs:
    solution: '**/*.sln'
    msbuildArchitecture: 'x64'
    platform: 'Any CPU'
    configuration: '$(buildConfiguration)'

- task: NuGetCommand@2
  displayName: 'nuget setApiKey'
  inputs:
    command: 'custom'
    arguments: 'setApiKey $(nugetCredential)'

- task: NuGetCommand@2
  displayName: 'nuget push'
  inputs:
    command: 'push'
    feedsToUse: 'config'    
    externalFeedCredentials: '$(externalFeedCredentials)' 
    publishFeedCredentials: '$(publishFeedCredentials)'    
    packagesToPush: '.net/src/DevSkill.SSLCommerz/DevSkill.SSLCommerz.Core/bin/Release/*.nupkg;!.net/src/DevSkill.SSLCommerz/DevSkill.SSLCommerz.Core/bin/Release/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'DevSkill.SSLCommerz.Core'
    versioningScheme: 'off'
    allowPackageConflicts: true
