# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
- staging
- dev

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  projects: '**/**/*.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  inputs:
    name: '' 
    command: 'restore'
    projects: '**/**/*.csproj'
    workingDirectory: '.net./src'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/**/*.csproj'
    workingDirectory: '.net./src'

- task: NuGetToolInstaller@1
  inputs:
    versionSpec: 
    checkLatest: true

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/**/*.sln'
    feedsToUse: 'select'

- task: MSBuild@1
  inputs:
    solution: '**/**/*.csproj'
    msbuildArchitecture: 'x64'
    platform: 'Any CPU'
    configuration: 'Debug'
